export const serviceCategories = [
  {
    id: "aarambh",
    title: "AARAMBH",
    badge: "Start Your Business",
    icon: "💎",
    description: "Launch your business with expert guidance on Private Limited, NGO, and Partnership registration.",
    services: [
      "Private Limited Company Incorporation",
      "One Person Company (OPC) Registration",
      "Limited Liability Partnership (LLP) Registration",
      "Partnership Firm Registration (ROF)",
      "Section 8 Company",
      "12A and 80G Registration",
      "NGO Darpan",
    ],
  },
  {
    id: "kavach",
    title: "KAVACH",
    badge: "Protect Your Business",
    icon: "🛡️",
    description: "Secure your intellectual property through trademark registration and legal protection.",
    services: [
      "Shram Suvidha Registration",
      "Trademark Registration",
      "Patent Registration",
      "Copyright Registration",
    ],
  },
  {
    id: "pramanit",
    title: "PRAMANIT",
    badge: "Get Certified",
    icon: "📜",
    description: "Navigate business compliance, tax auditing, and essential business certifications with ease.",
    services: [
      "Startup India Certification",
      "GeM Registration",
      "Tax Exemption Certificate",
      "ZED Certificate",
      "ISO Certificate",
      "GST Registration & Certificate",
      "FSSAI Certificate",
      "IEC Certificate",
      "Udhyam Registration",
    ],
  },
  {
    id: "nidhi",
    title: "NIDHI",
    badge: "Raising Funds",
    icon: "💰",
    description: "Unlock MSME support schemes and tailored government grants for financial stability.",
    services: [
      "Government Funding",
      "Investor Pitch Deck",
      "Financial Modeling & Valuation Reports",
      "Project Report (CMA Data)",
    ],
  },
  {
    id: "vikas",
    title: "VIKAS",
    badge: "Scaling & Growth",
    icon: "📈",
    description: "Fuel your business growth with venture capital expertise and government loan assistance.",
    services: [
      "Marketing & Sales Consultancy",
      "Digital Presence & Social Media Handling",
      "Website & App Design/Development",
      "Brand Identity",
    ],
  },
  {
    id: "vistar",
    title: "VISTAR",
    badge: "Expanding Horizons",
    icon: "🚀",
    description: "Elevate your brand with logo design, digital marketing, and modern website development.",
    services: [
      "E-Commerce Registration",
      "Export Consultancy",
      "Franchise Model Development",
      "CRM/ERP Solutions",
    ],
  },
  {
    id: "prabandhit",
    title: "PRABANDHIT",
    badge: "Manage Your Business",
    icon: "⚖️",
    description: "Comprehensive business management, compliance, and recruitment solutions.",
    services: [
      "Accounting and Bookkeeping Services",
      "Compliance Management",
      "GST Compliance",
      "Recruitment Services",
      "BHASKAR ID",
    ],
  },
];

export const allServices = serviceCategories.flatMap(cat => cat.services);
